# Please see the documentation for all configuration options:
# https://docs.github. com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot. yml-file
version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
    assignees:
      - 'lc-2025'
    commit-message:
      prefix: 'chore: '
    labels:
      - 'dependencies'
      - 'npm'
    pull-request-branch-name:
      separator: '/'
    # Filter updates by type
    allow:
      - dependency-type: 'direct'
    versioning-strategy: 'auto'
